name: Build Dynamic Libraries

permissions:
  contents: write

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  release-dyn-libs:
    runs-on: ubuntu-latest
    name: Build and Release Dynamic Libraries
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      # TODO Try to find something cheaper than the whole `cargo xtask build`, we just need the dynamic libraries
      - name: Build dynamic libraries
        run: cargo xtask build

      - name: Get short commit hash
        id: commit
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create release archive
        run: |
          cd target/deploy
          zip -r ../../solana-dynamic-libraries-${{ steps.commit.outputs.short_sha }}.zip *.so

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: solana-dynamic-libraries-${{ steps.commit.outputs.short_sha }}.zip
          tag_name: dyn-libs-${{ steps.commit.outputs.short_sha }}
          name: Dynamic Libraries Release ${{ steps.commit.outputs.short_sha }}
          body: |
            Dynamic libraries built from commit ${{ github.sha }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger relayer workflow
        run: |
          # TODO point at the eigerco repo
          # TODO get a PAT
          curl -X POST \
            -H "Authorization: token ${{ secrets.RELAYER_DISPATCH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/pierre-l/axelar-solana-relayer/dispatches \
            -d '{
              "event_type": "dynamic_libraries_updated",
              "client_payload": {
                "repository": "${{ github.repository }}",
                "release_tag": "dyn-libs-${{ steps.commit.outputs.short_sha }}",
                "commit_sha": "${{ github.sha }}",
                "short_sha": "${{ steps.commit.outputs.short_sha }}",
                "download_url": "https://github.com/${{ github.repository }}/releases/download/dyn-libs-${{ steps.commit.outputs.short_sha }}/solana-dynamic-libraries-${{ steps.commit.outputs.short_sha }}.zip"
              }
            }'
            # TODO Print the URL of the triggered workflow run