name: Build Dynamic Libraries

permissions:
  contents: read

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  release-dyn-libs:
    runs-on: ubuntu-latest
    name: Build and Release Dynamic Libraries
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup repo
        uses: ./.github/actions/setup-repo

      - name: Build dynamic libraries
        run: cargo xtask build

      - name: Get short commit hash
        id: commit
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create release archive
        run: |
          cd target/deploy
          zip -r ../../solana-dynamic-libraries-${{ steps.commit.outputs.short_sha }}.zip *.so

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: solana-dynamic-libraries-${{ steps.commit.outputs.short_sha }}.zip